services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}        
      ORACLE_DATABASE: FREEPDB1
      APP_USER: synergia              
      APP_USER_PASSWORD: ${ORACLE_APP_PASSWORD}
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ../database/oracle-init/01_init.sh:/opt/oracle/scripts/startup/01_init.sh
      - ../database/oracle-init/synergia_oracle.sql:/opt/oracle/scripts/setup/synergia_oracle.sql

    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 10s
      retries: 20          
      start_period: 60s
    restart: unless-stopped


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: my-rabbit
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"   # puerto métricas prometheus
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  rest_api:
    build:
      context:  ../..
      dockerfile:  infra/docker/Dockerfile
    container_name: rest_api
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload --log-level debug --access-log
    volumes:
      - ../src:/app
      - ./storage:/app/storage   # persistir archivos subidos
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  ws_api:
    build: 
      context: ../..
      dockerfile: infra/docker/Dockerfile
    container_name: ws_api
    command: uvicorn ws_api:app --host 0.0.0.0 --port 8001 --reload --log-level debug --access-log
    volumes:
      - ../src:/app
    ports:
      - "8001:8001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - rest_api
      - ws_api
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=marcusolsson-dynamictext-panel
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

  test:
    build: .
    container_name: test_api
    command: pytest tests/ -v --tb=short
    volumes:
      - ../src:/app

    profiles: [test]
    environment:
      - PYTHONPATH=/app

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: ["start", "--all", "--config", "/etc/ngrok.yml"]
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    volumes:
      - ../ngrok/ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"
    depends_on:
      - rest_api
      - ws_api


volumes:
  oracle_data:
  mariadb_data:
  rabbitmq_data:
  prometheus_data:
  grafana_data:
